default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST") { "localhost" } %>
  username: <%= ENV.fetch("DATABASE_USER") { "bonz" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "" } %>

development:
  <<: *default
  database: gallery_api_development

test:
  <<: *default
  database: gallery_api_test

production:
  <<: *default
  database: gallery_api_production
  username: gallery_api
  password: <%= ENV['GALLERY_API_DATABASE_PASSWORD'] %>
